### ISSUE TITLE
Missing iOS header content in overlay

### ISSUE THREAD

**Issue by kristfal** [intercom/intercom-cordova#217] opened 2017-11-08 12:02 UTC
## Version info
  Intercom for Cordova/PhoneGap version: 1.1.7
  iOS/Android OS version: iOS 11+

## Expected behavior

Intercom provides content in the header (back and close button + title)

## Actual behavior

Intercom overlay header content is invisible. See screenshot:

![img_0002](https://user-images.githubusercontent.com/5638107/32548002-6786bf20-c484-11e7-8a59-aa4d27589bbb.PNG)

This issue was introduced with iOS 11 as far as I can tell, but I'm not 100% certain. Right now, we're stuck on Cordova iOS 3.9.2, so we can't upgrade to the latest Intercom plugin version (which probably has a fix for this).

We're wondering if there is some kind of hotfix or workaround we can do on our end to mitigate this for a couple of weeks before we are able to upgrade to a more recent version of Intercom.

**Comment by skylerwshaw** [comment] 2017-11-08 16:06
Hey @kristfal, can you share your Cordova dependencies? There are several strange things happening with the Intercom display in this screenshot that we're unable to reproduce. It appears that there might be a conflict such as another dependency swizzling or overriding our presentation behavior. 

Are you able to reproduce this with our sample app?:
https://github.com/intercom/intercom-cordova/tree/master/Example

Also, a video or additional screenshots showing this behavior might surface more about what's going on. It's hard to see what elements are modified with this mostly-white screenshot.

Thank you!

**Comment by jtreanor** [comment] 2017-11-09 15:01
@kristfal The plugin version your are using is extremely old (1.1.7 was released in June 2016).

The latest version of the plugin is 4.1.0. Updating should resolve your issue.

**Closed** 2017-12-21 12:39 UTC
