### ISSUE TITLE
Intercom crashes app on second open Android

### ISSUE THREAD

**Issue by christoffer-Van** [intercom/intercom-cordova#177] opened 2017-04-27 22:58 UTC
## Version info
  - Intercom for Cordova/PhoneGap version: 3.1.3
  - iOS/Android OS version: 6.0.1/7.x.x/7.x.x
  - iOS/Android Device: OnePlusX/Pixel/Nexus 6

## Expected behavior
Should open and close chat window.

## Actual behavior
Opens chat window no problem first time, and closes it just fine. Second time I click, it opens the chat window, then crashes the app 2sec later. Reproduced on 2 phones(onePlus and Pixel). Works on the Nexus 6 though...

## Steps to reproduce
 1. Open, close chat. Open chat, crash.

## Logs

**Comment by bboyle18** [comment] 2017-04-27 23:08
Hi @christoffer-Van 👋

Can you provide us with some crash logs for this please? Otherwise we won't be able to investigate and solve the issue for you. 

Cheers

Brian

**Comment by bboyle18** [comment] 2017-04-28 15:49
Closing. Feel free to re-open if you can provide a more detailed issue report with logs.
Brian

**Closed by bboyle18** 2017-04-28 15:49 UTC
Labels: needs info

**Comment by christoffer-Van** [comment] 2017-05-02 00:10
```
[ 05-01 17:09:39.170  2001: 5319 I/ActivityManager ]
START u0 {flg=0x10000000 cmp=com.wealthbar.ios/io.intercom.android.sdk.activities.IntercomMessengerActivity (has extras)} from uid 10196 pid 1345 on display 0

[ 05-01 17:09:39.192  1345: 1345 D/CordovaActivity ]
Paused the activity.

[ 05-01 17:09:39.192  1345: 1345 D/AppTracker ]
App Event: stop

[ 05-01 17:09:39.206  5323: 5323 W/Binder_F ]
type=1400 audit(0.0:40270): avc: denied { ioctl } for path="socket:[3469967]" dev="sockfs" ino=3469967 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0

[ 05-01 17:09:39.206  5323: 5323 W/Binder_F ]
type=1400 audit(0.0:40271): avc: denied { ioctl } for path="socket:[3469967]" dev="sockfs" ino=3469967 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0

[ 05-01 17:09:39.229  1345: 1345 V/BoostFramework ]
BoostFramework() : mPerf = com.qualcomm.qti.Performance@db20757

[ 05-01 17:09:39.229  1345: 1345 V/BoostFramework ]
BoostFramework() : mPerf = com.qualcomm.qti.Performance@753d244

[ 05-01 17:09:39.226  5324: 5324 W/Binder_10 ]
type=1400 audit(0.0:40272): avc: denied { ioctl } for path="socket:[3470352]" dev="sockfs" ino=3470352 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0

[ 05-01 17:09:39.226  5324: 5324 W/Binder_10 ]
type=1400 audit(0.0:40273): avc: denied { ioctl } for path="socket:[3470352]" dev="sockfs" ino=3470352 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0

[ 05-01 17:09:39.271  1345: 1345 V/BoostFramework ]
BoostFramework() : mPerf = com.qualcomm.qti.Performance@cea53f

[ 05-01 17:09:39.272  1345: 1345 V/BoostFramework ]
BoostFramework() : mPerf = com.qualcomm.qti.Performance@c0fbe0c

[ 05-01 17:09:39.276  1345: 1345 D/AppTracker ]
App Event: start

[ 05-01 17:09:39.276  4724: 4724 W/Binder_8 ]
type=1400 audit(0.0:40274): avc: denied { ioctl } for path="socket:[3470354]" dev="sockfs" ino=3470354 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0

[ 05-01 17:09:39.276  4724: 4724 W/Binder_8 ]
type=1400 audit(0.0:40275): avc: denied { ioctl } for path="socket:[3470354]" dev="sockfs" ino=3470354 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0

[ 05-01 17:09:39.364  1345: 1345 D/AbstractTracker ]
Event success

[ 05-01 17:09:39.399  1345: 1345 D/AbstractTracker ]
Event success

[ 05-01 17:09:39.399  2001: 2032 I/ActivityManager ]
Displayed com.wealthbar.ios/io.intercom.android.sdk.activities.IntercomMessengerActivity: +203ms

[ 05-01 17:09:39.396  2013: 2013 W/Binder_1 ]
type=1400 audit(0.0:40276): avc: denied { ioctl } for path="socket:[3465826]" dev="sockfs" ino=3465826 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0

[ 05-01 17:09:39.396  2013: 2013 W/Binder_1 ]
type=1400 audit(0.0:40277): avc: denied { ioctl } for path="socket:[3465826]" dev="sockfs" ino=3465826 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0

[ 05-01 17:09:39.521 32479:32479 D/wpa_supplicant ]
wlan0: Control interface command 'SIGNAL_POLL'

[ 05-01 17:09:39.524 32479:32479 D/wpa_supplicant ]
CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48

[ 05-01 17:09:41.233  1345: 1345 D/AndroidRuntime ]
Shutting down VM


[ 05-01 17:09:41.240  1345: 1345 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.wealthbar.ios, PID: 1345
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
	at android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:515)
	at android.support.v7.widget.DefaultItemAnimator.animateMove(DefaultItemAnimator.java:255)
	at android.support.v7.widget.DefaultItemAnimator.animateChange(DefaultItemAnimator.java:317)
	at android.support.v7.widget.SimpleItemAnimator.animateChange(SimpleItemAnimator.java:149)
	at android.support.v7.widget.RecyclerView$4.processPersistent(RecyclerView.java:530)
	at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:241)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3605)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3275)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5445)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5445)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5445)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5445)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5445)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5445)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5445)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5445)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5445)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2684)
	at android.view.View.layout(View.java:16692)
	at android.view.ViewGroup.layout(ViewGroup.java:5445)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2178)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1938)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1114)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6068)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(Activity

[ 05-01 17:09:41.240  1345: 1345 D/AppTracker ]
App Event: crash

[ 05-01 17:09:41.252  2001: 4554 W/ActivityManager ]
  Force finishing activity com.wealthbar.ios/io.intercom.android.sdk.activities.IntercomMessengerActivity

[ 05-01 17:09:41.254  2001: 1751 W/DropBoxManagerService ]
Dropping: data_app_crash (10 > 0 bytes)

[ 05-01 17:09:41.273  2001: 2026 V/BoostFramework ]
BoostFramework() : mPerf = com.qualcomm.qti.Performance@e336e5e

[ 05-01 17:09:41.273  2001: 2026 V/BoostFramework ]
BoostFramework() : mPerf = com.qualcomm.qti.Performance@23ad23f

[ 05-01 17:09:41.310  2001:19487 I/OpenGLRenderer ]
Initialized EGL, version 1.4

[ 05-01 17:09:41.759  2001: 2025 W/ActivityManager ]
Activity pause timeout for ActivityRecord{12ab629 u0 com.wealthbar.ios/io.intercom.android.sdk.activities.IntercomMessengerActivity t5108 f}

[ 05-01 17:09:42.533 32479:32479 D/wpa_supplicant ]
wlan0: Control interface command 'SIGNAL_POLL'

[ 05-01 17:09:42.548 32479:32479 D/wpa_supplicant ]
CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48

[ 05-01 17:09:45.559 32479:32479 D/wpa_supplicant ]
wlan0: Control interface command 'SIGNAL_POLL'

[ 05-01 17:09:45.577 32479:32479 D/wpa_supplicant ]
CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48

[ 05-01 17:09:46.188   432:  432 I/Gobi     ]
vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:2500: GetTransState() EBADF


[ 05-01 17:09:46.188   432:  432 I/Gobi     ]
vendor/qcom/proprietary/RIDL/RIDLClient/MainCore.cpp:1550: Failed to get TransState, rc 9


[ 05-01 17:09:46.188   432:  432 I/Gobi     ]
vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:2500: GetTransState() EBADF


[ 05-01 17:09:46.188   432:  432 I/Gobi     ]
vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:2500: GetTransState() EBADF


[ 05-01 17:09:48.588 32479:32479 D/wpa_supplicant ]
wlan0: Control interface command 'SIGNAL_POLL'

[ 05-01 17:09:48.606 32479:32479 D/wpa_supplicant ]
CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48

[ 05-01 17:09:51.266  2001: 2025 W/ActivityManager ]
Launch timeout has expired, giving up wake lock!

[ 05-01 17:09:51.611 32479:32479 D/wpa_supplicant ]
wlan0: Control interface command 'SIGNAL_POLL'

[ 05-01 17:09:51.628 32479:32479 D/wpa_supplicant ]
CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=163840 outq=0 send_len=48

[ 05-01 17:09:53.266  2001:32665 E/         ]
qsap_get_mode: ioctl Get Mode = 2


[ 05-01 17:09:53.266  2001:32665 D/QCLDR-   ]
HOSTAPD Disabled


[ 05-01 17:09:54.637 32479:32479 D/wpa_supplicant ]
```

**Comment by jtuchek** [comment] 2017-12-06 23:58
@bboyle18 also running into this issue, except on different devices than the original poster.

Intercomm dependencies:
    compile 'io.intercom.android:intercom-sdk-base:3.2.8'
    compile 'io.intercom.android:intercom-sdk-fcm:3.2.8'

Android device:
- Nvidia Shield @ Android 7.0

```12-06 17:52:13.668 22024-22024/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: [application-id], PID: 22024
                                                   java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
                                                       at android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:515)
                                                       at android.support.v7.widget.DefaultItemAnimator.animateAdd(DefaultItemAnimator.java:218)
                                                       at android.support.v7.widget.SimpleItemAnimator.animateAppearance(SimpleItemAnimator.java:114)
                                                       at android.support.v7.widget.RecyclerView.animateAppearance(RecyclerView.java:3804)
                                                       at android.support.v7.widget.RecyclerView$4.processAppeared(RecyclerView.java:521)
                                                       at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:247)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3653)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3323)
                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                       at android.view.View.layout(View.java:17519)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                       at android.view.View.layout(View.java:17519)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                       at android.view.View.layout(View.java:17519)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                       at android.view.View.layout(View.java:17519)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                       at android.view.View.layout(View.java:17519)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                       at android.view.View.layout(View.java:17519)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                       at android.view.View.layout(View.java:17519)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                       at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1730)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1496)
                                                       at android.view.View.layout(View.java:17519)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                       at android.view.View.layout(View.java:17519)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                       at android.view.View.layout(View.java:17519)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                       at android.view.View.layout(View.java:17519)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                       at android.view.View.layout(View.java:17519)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                       at com.android.internal.policy.DecorView.onLayout(DecorView.java:724)
                                                       at android.view.View.layout(View.java:17519)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5612)```

**Comment by ghiculescu** [comment] 2017-12-18 11:46
@bboyle18 any ideas here? we are seeing lots of similar crashes in google play

```
java.lang.NoClassDefFoundError: 
  at android.support.v7.widget.DefaultItemAnimator.resetAnimation (DefaultItemAnimator.java:515)
  at android.support.v7.widget.DefaultItemAnimator.animateMove (DefaultItemAnimator.java:255)
  at android.support.v7.widget.DefaultItemAnimator.animateChange (DefaultItemAnimator.java:317)
  at android.support.v7.widget.SimpleItemAnimator.animateChange (SimpleItemAnimator.java:149)
  at android.support.v7.widget.RecyclerView$4.processPersistent (RecyclerView.java:501)
  at android.support.v7.widget.ViewInfoStore.process (ViewInfoStore.java:241)
  at android.support.v7.widget.RecyclerView.dispatchLayoutStep3 (RecyclerView.java:3449)
  at android.support.v7.widget.RecyclerView.dispatchLayout (RecyclerView.java:3199)
  at android.support.v7.widget.RecyclerView.onLayout (RecyclerView.java:3632)
  at android.view.View.layout (View.java:18874)
  at android.view.ViewGroup.layout (ViewGroup.java:5954)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:323)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:261)
  at android.view.View.layout (View.java:18874)
  at android.view.ViewGroup.layout (ViewGroup.java:5954)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:323)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:261)
  at android.view.View.layout (View.java:18874)
  at android.view.ViewGroup.layout (ViewGroup.java:5954)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:323)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:261)
  at android.view.View.layout (View.java:18874)
  at android.view.ViewGroup.layout (ViewGroup.java:5954)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:323)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:261)
  at android.view.View.layout (View.java:18874)
  at android.view.ViewGroup.layout (ViewGroup.java:5954)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:323)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:261)
  at android.view.View.layout (View.java:18874)
  at android.view.ViewGroup.layout (ViewGroup.java:5954)
  at android.widget.LinearLayout.setChildFrame (LinearLayout.java:1741)
  at android.widget.LinearLayout.layoutVertical (LinearLayout.java:1585)
  at android.widget.LinearLayout.onLayout (LinearLayout.java:1494)
  at android.view.View.layout (View.java:18874)
  at android.view.ViewGroup.layout (ViewGroup.java:5954)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:323)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:261)
  at android.view.View.layout (View.java:18874)
  at android.view.ViewGroup.layout (ViewGroup.java:5954)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:323)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:261)
  at android.view.View.layout (View.java:18874)
  at android.view.ViewGroup.layout (ViewGroup.java:5954)
  at android.widget.FrameLayout.layoutChildren (FrameLayout.java:323)
  at android.widget.FrameLayout.onLayout (FrameLayout.java:261)
  at com.android.internal.policy.DecorView.onLayout (DecorView.java:935)
  at android.view.View.layout (View.java:18874)
  at android.view.ViewGroup.layout (ViewGroup.java:5954)
  at android.view.ViewRootImpl.performLayout (ViewRootImpl.java:2697)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2413)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1550)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7189)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:959)
  at android.view.Choreographer.doCallbacks (Choreographer.java:734)
  at android.view.Choreographer.doFrame (Choreographer.java:670)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:945)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:380)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
```

config.xml contains:

`<plugin name="cordova-plugin-intercom" spec="~3.0.26" />`
`<plugin name="phonegap-plugin-push" spec="https://github.com/intercom/phonegap-plugin-push.git">`

**Comment by ronocod** [comment] 2017-12-18 13:20
Those crashes are caused by your app using Support Library dependencies with inconsistent versions. Are you seeing any error messages from Intercom when you run `cordova build android` with the latest version of our plugin?
