### ISSUE TITLE
Compatibility with push plugin

### ISSUE THREAD

**Issue by elliotstokes** [intercom/intercom-cordova#3] opened 2015-05-29 13:54 UTC
Im getting a build error when trying to build this on android. I think because of the gcm libs from push plugin.

I get the error:

  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:302)
  		at com.android.dx.command.dexer.Main.run(Main.java:245)
  		at com.android.dx.command.dexer.Main.main(Main.java:214)
  		at com.android.dx.command.Main.main(Main.java:106)

Any ways we can work around this?

**Comment by elliotstokes** [comment] 2015-05-29 14:12
I have got around it by removing the gcm dependency from the gradle file but I suspect its going to be a common problem for anyone who has implemented push into their app.

**Comment by Anu2g** [comment] 2015-05-29 14:14
Hey Elliot, could you explain your solution to this a bit more? I've been struggling with this the last few days, and have been contemplating updating PushPlugin to use the latest google-play-services.gcm lib (instead of gcm.jar), because I thought both gcm and google-play-services.gcm couldn't be used in unison. Thanks in advance!

**Comment by jtreanor** [comment] 2015-05-29 14:21
Thanks @elliotstokes. Yes I agree this will most likely be quite a common issue. Unfortunately I don't see an easy fix from our side.

The problem is that our dependency on `com.google.android.gms` (https://github.com/intercom/intercom-cordova/blob/master/src/android/intercom.gradle#L15) is fighting with PushPlugin's `gcm.jar`. The same problem can exist for the support library.

As @elliotstokes has found, the manual fix is to make both plugins use the same version (ours is much newer so it would be preferable to remove theirs). This is not great though.
If PushPlugin used Gradle this would be much easier to solve.

I am very much open to suggestions here. My Cordova experience is somewhat limited.

**Comment by Anu2g** [comment] 2015-05-29 14:25
@jtreanor Making PushPlugin use google-play-services.gcm isn't completely straightforward. I took a quick look last night. I was surprised to see that such a popularly used plugin (with so many open pull requests) didn't have a single pull request updating gcm to play services. Unfortunately, I think updating PushPlugin to use play-services is the only real solution. Frankly, this conflict has been the bottleneck for adding Intercom to our project

**Comment by elliotstokes** [comment] 2015-05-29 14:25
I don't really think there is an easy fix in the cordova plugin. 

https://github.com/intercom/intercom-android/issues/50 

would probably fix it though.

**Comment by elliotstokes** [comment] 2015-05-29 14:30
Also as mentioned by @Anu2g it's not as easy as deleting the gcm.jar file as I think it contains more than just the play services libs.

**Comment by Anu2g** [comment] 2015-05-29 14:41
@elliotstokes what happens when you remove the gcm.jar dependency? The PushPlugin breaks, right?

**Comment by elliotstokes** [comment] 2015-05-29 14:42
Yeah I can't compile.If I remove the gcm dependency from the gradle file though I can get it to build.

**Comment by jtreanor** [comment] 2015-05-29 14:47
Thanks @elliotstokes And @Anu2g 

Unfortunately I don't believe https://github.com/intercom/intercom-android/issues/50 will work because I don't think there is any way we can namespace Google Play Services.

I am going to spend some time in the next few days digging a bit deeper into this.

**Comment by elliotstokes** [comment] 2015-05-29 14:51
Thanks

**Comment by Anu2g** [comment] 2015-05-29 15:01
Thank you sir. I'm here, as well as my team, to help in any way we can. We're going public with an app very soon, and were hoping to get Intercom into our system by the end of this week so we could get in our private beta users hands before we put it on app stores. This was a bottleneck for us (because it also forced us to update our Cordova version), but long story short, my team and I have prioritized getting this working so we're able to help. Just let me know how we can help @elliotstokes !

**Comment by jtreanor** [comment] 2015-05-29 16:21
Thanks @Anu2g, any contribution is welcome however I don't foresee there being a straightforward fix here.

Potentially the best immediate fix would be to fork PushPlugin to use updated support library and play services jars. Not sure how easy this will be but I'll try it out.

**Comment by Anu2g** [comment] 2015-05-29 16:31
@jtreanor I agree...that was the course of action we were thinking to take before this conversation started. A bunch of the classesf/unction calls to GCM seem to have easy-to-find analogous classes/functions in play-services, but I'm not too experienced at using either library, so not sure how long it'd take. I'm extremely interested in your results on that. Feel free to ping me on hangouts @ anu@hurdlr.com if I/we can be helpful.

**Comment by jtreanor** [comment] 2015-05-29 20:15
I will look into a fork and post here with any progress.

**Comment by jtreanor** [comment] 2015-06-05 14:43
I have opened a PR with improved push notifications support. This means PushPlugin is no longer needed to support Intercom push notifications. Details on how to support push are [here](https://github.com/intercom/intercom-cordova/blob/jtreanor/1.0.1/README.md#push-notifications).

If you still wish to use PushPlugin for non Intercom push notifications, you will have to use the fork I have created [here](https://github.com/intercom/PushPlugin). To install it, just run:

```
cordova plugin add https://github.com/intercom/PushPlugin.git
```

The changes I have made can be seen in https://github.com/intercom/PushPlugin/commit/bddd917b3f273cf7e829b9286f7946ac2a575f14. It just excludes Intercom push messages from being handled and updates the support library so there are no build errors.

Let me know if you have any questions or feedback.

@elliotstokes I believe in your case you may still have a build error. I have confirmed that `play-services-gcm` and the old `gcm.jar` which is used in PushPlugin can coexist peacefully. I suspect some other plugin in your app is also using Google Play Services, so you will have to update it.

**Comment by jtreanor** [comment] 2015-06-05 15:14
I didn't mean to close this straight away.

**Comment by elliotstokes** [comment] 2015-06-05 15:53
Ill take a look at this next week. Thanks

**Closed** 2015-06-12 17:09 UTC

**Comment by carlosjavier84** [comment] 2015-06-28 08:59
I had the same incompatibility issue with the Facebook connect plugin and I fixed it excluding the support-v4 from play-services-gcm:

```compile ('com.google.android.gms:play-services-gcm:7.5.0'){
        exclude module: 'support-v4'
    }```

https://github.com/carlosjavier84/intercom-cordova/commit/8ba8955b2a27279628e304fa578402aabcc4bccc
