### ISSUE TITLE
Notification Push on Android doesn't work :(

### ISSUE THREAD

**Issue by PRotig** [intercom/intercom-cordova#165] opened 2017-03-22 10:53 UTC
## Version info
  - Intercom for Cordova/PhoneGap version: 3.1.0
  - iOS/Android OS version: 5.0.1
  - iOS/Android Device: Samsung Galaxy S4 (GT-I9505)

Cordova CLI: 6.5.0
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.9.1 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 8.2.1 Build version 8C1002 

In the config.xml 
```
<platform name="android">
        <preference name="intercom-app-id" value="xxxxxxx" />
        <preference name="intercom-android-api-key" value="android_sdk-xxxxxx" />
        <preference name="intercom-android-sender-id" value="xxxxxx" />
        <preference name="intercom-android-push-type" value="GCM"/>
```
Of course, the xxx has the good values, I think...

## Expected behavior
When Intercom shoot a message to a user (from a conversation or manual message), the device should receive a push notification ! 

## Actual behavior
Nothing happen :( 
I can't see a special problem in logs...
**On iOs, working perfectly :)**

## Steps to reproduce
 1. Just write to user through Intercom
 2. Nothing happening.

## Logs

**Comment by bboyle18** [comment] 2017-03-23 12:05
Hi @PRotig 👋 

Would you be able to check the following please?
1. Is you Android API key correct? Can you receive inapp messages on Android?
2. Have you added your GCM API key to the Android settings page on Intercom?
3. Are you testing by sending a message to a registered user on Intercom while your Android app is in the background? If so, can you share the userId or Email of this user so we can check our logs?

Thanks

Brian

**Comment by PRotig** [comment] 2017-03-24 09:35
Hello @bboyle18 ,
Again me... Sorry...
My answer in order :
- I think my API Key is correct because we are using the onesignal product to push notifications aswell et it is working pretty well.
- Yes, the GCM API Key is registered in my intercom settings.
- Yes, I am testing by sending a message to a registered user on Intercom while my Android app is in the background. The userId is 5566, the mail is paul.test.15032@quatreepingles.fr
Thanks a lot
BTW, the intercom messenger is awesome.

**Comment by bboyle18** [comment] 2017-03-24 10:35
Thanks for this info @PRotig 👍  and glad you love Intercom 🎉 
I suspect that the issue is caused by the fact that you are using Onesignal for push notifications. We haven't tested Intercom with this so can't verify that it will work. We have also seen in the past that using other push providers can cause conflicts with Intercom and lead to push notifications not working.
The only other push provider we officially support and have a fork of their repo is https://github.com/intercom/phonegap-plugin-push.

Cheers

Brian

**Comment by jtreanor** [comment] 2017-03-28 14:19
@PRotig Just a quick follow up here. Could you try this out with OneSignal uninstalled so that we can verify the issue is a conflict with OneSignal?

**Comment by jtreanor** [comment] 2017-03-31 13:39
Hi @PRotig,

Compatibility with our GCM providers has been fixed in [3.1.2](https://github.com/intercom/intercom-cordova/releases/tag/3.1.2). This should resolve your issue.

If you're still having problems, please let us know 😄

**Closed by jtreanor** 2017-03-31 13:39 UTC

**Comment by PRotig** [comment] 2017-04-02 15:52
Hello guys, @jtreanor @bboyle18 
Sorry for the delay, impossible for me to test these passed days.

**Just tried 3.1.2, still not working :(**

Is there a specific thing to do to uninstall / install new version ?

Thanks a lot

**Comment by jtreanor** [comment] 2017-04-03 09:23
@PRotig There is no specific procedure for updating. Before re-opening, can you verify that this snippet is present in your `AndroidManifest.xml`?

```
<service
    android:name="io.intercom.android.sdk.IntercomIntentService"
    android:exported="false">
    <intent-filter
        android:priority="999">
        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
    </intent-filter>
</service>
```

Also, it would be great if you could see if you have the same behaviour both with and without OneSignal.

**Comment by PRotig** [comment] 2017-04-04 14:58
Hello guys, @jtreanor @bboyle18 
Still not working :(
My manifest seems to be correct.
Just tried to remove OneSignal, but still nothing.
Do you want my key, token, etc..? to test it from your side ?

Btw, I opened another ticket because since the 3.1.2, I can't install the plugin on iOs anymore..

**Comment by jtreanor** [comment] 2017-04-04 15:13
I have added a reply to your other issue in #169. We can help you with your integration issues through our support channels.
