### ISSUE TITLE
Access to Help Center within messenger

### ISSUE THREAD

**Issue by FabPey** [intercom/intercom-cordova#163] opened 2017-03-21 16:20 UTC
Hi guys

We use your javascript API on another part of our service, and it has this great feature, when someone asks a question, it sends back a link to the help center, which the user can browse without leaving messenger. We would really need to see this in the cordova plugin to be able to use intercom as our main support tool, which is the plan - can you guys help ;-)

Thanks

**Comment by skylerwshaw** [comment] 2017-03-21 16:29
@FabPey Thank you for the well thought-out feature request. We're looking into adding this functionality but I don't have a timeline to share at this point. As this is not a bug, I'll close the issue but feel free to contact us through the Intercom in-app messenger on your Intercom dashboard for updates! Best, Skyler

**Closed by skylerwshaw** 2017-03-21 16:29 UTC

**Comment by FabPey** [comment] 2017-05-13 15:08
Hi there, just wondering if I could get a status update on this - Just worth mentioning, it's not really a feature request but a request to get the same features as the javascript messenger as the link to the help center is already shown there when user sends a question - it's badly missed in the cordova version to be honest as we want to use the help center (which we're paying for) - many thanks in advance.

**Comment by bboyle18** [comment] 2017-05-15 11:32
Hi @FabPey 
Thanks for getting in touch again.
Our product team have been discussing this a lot and we do have plans on our roadmap for this. 
Unfortunately we don't have any specific timeline we can share with you at the minute. 

Can you tell me what your company name is in Intercom? Our Educate Product Manager would like to get in touch with you to chat about this some more.

Cheers

Brian

**Comment by FabPey** [comment] 2017-05-15 12:06
Hi Brian


It's Herdwatch. I can be contacted on +353872025471


Fabien


________________________________

**Comment by bboyle18** [comment] 2017-05-15 12:19
Thanks @FabPey 
Found you on Intercom, so I'll send you details onto our PM.

Brian

**Comment by FabPey** [comment] 2017-08-20 18:09
Hi there, this issue was highlighted 5 months ago - any chance of getting the same functionality as is already available in the web version for a long time? That's all we're asking for ;-) and it is critical for us as the aim of using intercom is to better support our thousands of customers, which means auto-suggesting appropriate help center articles when they send us a question via the messenger in our cordova app.

Thanks in advance

**Comment by bboyle18** [comment] 2017-08-21 09:05
Hi @FabPey 
We haven't forgotten about this and we are actively working on Article Suggestions for our Mobile Messengers 😄 .
We'll have a new release soon, so keep an eye on the iOS and Android releases on GitHub as these will also be available for our Cordova Plugin.

Cheers

Brian

**Comment by FabPey** [comment] 2017-08-21 10:14
That's great news - thanks, looking forward to the update.

**Comment by bboyle18** [comment] 2017-09-09 12:48
Hi @FabPey 👋
We released article suggestions on mobile yesterday. 

Cheers 

Brian

**Comment by FabPey** [comment] 2017-09-09 13:00
Woohoo ;-) Thanks guys!

**Comment by FabPey** [comment] 2017-10-21 22:15
Hi @bboyle18 - unfortunately due to issues #204 #207 with Phonegap builds, we have had to use v3.2.2 of the plugin, and it seems the suggestions don't seem to be coming through - does it require v.4.0.0 of the plugin? I was hoping it was more of a backend thing - thanks.

**Comment by bboyle18** [comment] 2017-12-01 13:50
Hi @Coolcat13 👋 
Just thought I'd let you know that [Release 4.1.4](https://github.com/intercom/intercom-ios/releases/tag/4.1.4) of our iOS SDK includes an experimental feature to allow you to launch your Educate help center with from within your mobile app.

If you have any questions or feedback about it, please let me know 👍 
Brian
