### ISSUE TITLE
displayConversationsList(): iOS app crashes after device is tilted to landscape orientation

### ISSUE THREAD

**Issue by Mencls** [intercom/intercom-cordova#80] opened 2016-09-08 01:51 UTC
## Version info
- Intercom for Cordova/PhoneGap version: 3.0.9
- iOS/Android OS version: iOS 9.3.5
- iOS/Android Device: iPhone 5s, iPhone 6s
## Expected behavior

Should display the conversation list in landscape mode.
## Actual behavior

App crashes.
## Logs

<Error>: CGImageCreate: invalid image size: 0 x 0.
<Error>: CGContextSaveGState: invalid context 0x15a913850. Backtrace:
      <<redacted>+340>
       <-[GMSCALayer renderInContext:]+224>
        <-[GMSMapLayer renderInContext:]+128>
         <<redacted>+364>
          <<redacted>+788>
           <<redacted>+364>
            <<redacted>+788>
             <<redacted>+364>
              <<redacted>+788>
               <<redacted>+364>
                <<redacted>+788>
                 <<redacted>+364>
                  <<redacted>+788>
                   <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                    <_dispatch_call_block_and_release+24>
                     <_dispatch_client_callout+16>
                      <_dispatch_main_queue_callback_4CF+2096>
                       <<redacted>+12>
                        <<redacted>+1628>
                         <CFRunLoopRunSpecific+384>
                          <GSEventRunModal+180>
                           <UIApplicationMain+204>
                            <main+76>
<Error>: CGContextClipToRect: invalid context 0x15a913850. Backtrace:
      <<redacted>+396>
       <-[GMSCALayer renderInContext:]+224>
        <-[GMSMapLayer renderInContext:]+128>
         <<redacted>+364>
          <<redacted>+788>
           <<redacted>+364>
            <<redacted>+788>
             <<redacted>+364>
              <<redacted>+788>
               <<redacted>+364>
                <<redacted>+788>
                 <<redacted>+364>
                  <<redacted>+788>
                   <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                    <_dispatch_call_block_and_release+24>
                     <_dispatch_client_callout+16>
                      <_dispatch_main_queue_callback_4CF+2096>
                       <<redacted>+12>
                        <<redacted>+1628>
                         <CFRunLoopRunSpecific+384>
                          <GSEventRunModal+180>
                           <UIApplicationMain+204>
                            <main+76>
<Error>: CGContextSaveGState: invalid context 0x15a913850. Backtrace:
      <<redacted>+420>
       <-[GMSCALayer renderInContext:]+224>
        <-[GMSMapLayer renderInContext:]+128>
         <<redacted>+364>
          <<redacted>+788>
           <<redacted>+364>
            <<redacted>+788>
             <<redacted>+364>
              <<redacted>+788>
               <<redacted>+364>
                <<redacted>+788>
                 <<redacted>+364>
                  <<redacted>+788>
                   <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                    <_dispatch_call_block_and_release+24>
                     <_dispatch_client_callout+16>
                      <_dispatch_main_queue_callback_4CF+2096>
                       <<redacted>+12>
                        <<redacted>+1628>
                         <CFRunLoopRunSpecific+384>
                          <GSEventRunModal+180>
                           <UIApplicationMain+204>
                            <main+76><Error>: CGContextSaveGState: invalid context 0x15a913850. Backtrace:
      <<redacted>+528>
       <<redacted>+748>
        <-[GMSCALayer renderInContext:]+224>
         <-[GMSMapLayer renderInContext:]+128>
          <<redacted>+364>
           <<redacted>+788>
            <<redacted>+364>
             <<redacted>+788>
              <<redacted>+364>
               <<redacted>+788>
                <<redacted>+364>
                 <<redacted>+788>
                  <<redacted>+364>
                   <<redacted>+788>
                    <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                     <_dispatch_call_block_and_release+24>
                      <_dispatch_client_callout+16>
                       <_dispatch_main_queue_callback_4CF+2096>
                        <<redacted>+12>
                         <<redacted>+1628>
                          <CFRunLoopRunSpecific+384>
                           <GSEventRunModal+180>
                            <UIApplicationMain+204>
                             <main+76>
 <Error>: CGContextSetFillColorWithColor: invalid context 0x15a913850. Backtrace:
      <<redacted>+572>
       <<redacted>+748>
        <-[GMSCALayer renderInContext:]+224>
         <-[GMSMapLayer renderInContext:]+128>
          <<redacted>+364>
           <<redacted>+788>
            <<redacted>+364>
             <<redacted>+788>
              <<redacted>+364>
               <<redacted>+788>
                <<redacted>+364>
                 <<redacted>+788>
                  <<redacted>+364>
                   <<redacted>+788>
                    <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                     <_dispatch_call_block_and_release+24>
                      <_dispatch_client_callout+16>
                       <_dispatch_main_queue_callback_4CF+2096>
                        <<redacted>+12>
                         <<redacted>+1628>
                          <CFRunLoopRunSpecific+384>
                           <GSEventRunModal+180>
                            <UIApplicationMain+204>
                             <main+76>
<Error>: CGContextAddRect: invalid context 0x15a913850. Backtrace:
      <<redacted>+600>
       <<redacted>+748>
        <-[GMSCALayer renderInContext:]+224>
         <-[GMSMapLayer renderInContext:]+128>
          <<redacted>+364>
           <<redacted>+788>
            <<redacted>+364>
             <<redacted>+788>
              <<redacted>+364>
               <<redacted>+788>
                <<redacted>+364>
                 <<redacted>+788>
                  <<redacted>+364>
                   <<redacted>+788>
                    <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                     <_dispatch_call_block_and_release+24>
                      <_dispatch_client_callout+16>
                       <_dispatch_main_queue_callback_4CF+2096>
                        <<redacted>+12>
                         <<redacted>+1628>
                          <CFRunLoopRunSpecific+384>
                           <GSEventRunModal+180>
                            <UIApplicationMain+204>
                             <main+76>
<Error>: CGContextDrawPath: invalid context 0x15a913850. Backtrace:
      <<redacted>+616>
       <<redacted>+748>
        <-[GMSCALayer renderInContext:]+224>
         <-[GMSMapLayer renderInContext:]+128>
          <<redacted>+364>
           <<redacted>+788>
            <<redacted>+364>
             <<redacted>+788>
              <<redacted>+364>
               <<redacted>+788>
                <<redacted>+364>
                 <<redacted>+788>
                  <<redacted>+364>
                   <<redacted>+788>
                    <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                     <_dispatch_call_block_and_release+24>
                      <_dispatch_client_callout+16>
                       <_dispatch_main_queue_callback_4CF+2096>
                        <<redacted>+12>
                         <<redacted>+1628>
                          <CFRunLoopRunSpecific+384>
                           <GSEventRunModal+180>
                            <UIApplicationMain+204>
                             <main+76>
<Error>: CGContextRestoreGState: invalid context 0x15a913850. Backtrace:
      <<redacted>+632>
       <<redacted>+748>
        <-[GMSCALayer renderInContext:]+224>
         <-[GMSMapLayer renderInContext:]+128>
          <<redacted>+364>
           <<redacted>+788>
            <<redacted>+364>
             <<redacted>+788>
              <<redacted>+364>
               <<redacted>+788>
                <<redacted>+364>
                 <<redacted>+788>
                  <<redacted>+364>
                   <<redacted>+788>
                    <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                     <_dispatch_call_block_and_release+24>
                      <_dispatch_client_callout+16>
                       <_dispatch_main_queue_callback_4CF+2096>
                        <<redacted>+12>
                         <<redacted>+1628>
                          <CFRunLoopRunSpecific+384>
                           <GSEventRunModal+180>
                            <UIApplicationMain+204>
                             <main+76>
<Error>: CGContextSaveGState: invalid context 0x15a913850. Backtrace:
      <<redacted>+192>
       <<redacted>+788>
        <-[GMSCALayer renderInContext:]+224>
         <-[GMSMapLayer renderInContext:]+128>
          <<redacted>+364>
           <<redacted>+788>
            <<redacted>+364>
             <<redacted>+788>
              <<redacted>+364>
               <<redacted>+788>
                <<redacted>+364>
                 <<redacted>+788>
                  <<redacted>+364>
                   <<redacted>+788>
                    <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                     <_dispatch_call_block_and_release+24>
                      <_dispatch_client_callout+16>
                       <_dispatch_main_queue_callback_4CF+2096>
                        <<redacted>+12>
                         <<redacted>+1628>
                          <CFRunLoopRunSpecific+384>
                           <GSEventRunModal+180>
                            <UIApplicationMain+204>
                             <main+76>
<Error>: CGContextGetBaseCTM: invalid context 0x15a913850. Backtrace:
      <CGContextGetBaseCTM+92>
       <<redacted>+204>
        <<redacted>+788>
         <-[GMSCALayer renderInContext:]+224>
          <-[GMSMapLayer renderInContext:]+128>
           <<redacted>+364>
            <<redacted>+788>
             <<redacted>+364>
              <<redacted>+788>
               <<redacted>+364>
                <<redacted>+788>
                 <<redacted>+364>
                  <<redacted>+788>
                   <<redacted>+364>
                    <<redacted>+788>
                     <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                      <_dispatch_call_block_and_release+24>
                       <_dispatch_client_callout+16>
                        <_dispatch_main_queue_callback_4CF+2096>
                         <<redacted>+12>
                          <<redacted>+1628>
                           <CFRunLoopRunSpecific+384>
                            <GSEventRunModal+180>
                             <UIApplicationMain+204>
                              <main+76>
<Error>: CGContextConcatCTM: invalid context 0x15a913850. Backtrace:
      <<redacted>+280>
       <<redacted>+788>
        <-[GMSCALayer renderInContext:]+224>
         <-[GMSMapLayer renderInContext:]+128>
          <<redacted>+364>
           <<redacted>+788>
            <<redacted>+364>
             <<redacted>+788>
              <<redacted>+364>
               <<redacted>+788>
                <<redacted>+364>
                 <<redacted>+788>
                  <<redacted>+364>
                   <<redacted>+788>
                    <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                     <_dispatch_call_block_and_release+24>
                      <_dispatch_client_callout+16>
                       <_dispatch_main_queue_callback_4CF+2096>
                        <<redacted>+12>
                         <<redacted>+1628>
                          <CFRunLoopRunSpecific+384>
                           <GSEventRunModal+180>
                            <UIApplicationMain+204>
                             <main+76>
<Error>: CGContextSetBaseCTM: invalid context 0x15a913850. Backtrace:
      <<redacted>+348>
       <<redacted>+788>
        <-[GMSCALayer renderInContext:]+224>
         <-[GMSMapLayer renderInContext:]+128>
          <<redacted>+364>
           <<redacted>+788>
            <<redacted>+364>
             <<redacted>+788>
              <<redacted>+364>
               <<redacted>+788>
                <<redacted>+364>
                 <<redacted>+788>
                  <<redacted>+364>
                   <<redacted>+788>
                    <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                     <_dispatch_call_block_and_release+24>
                      <_dispatch_client_callout+16>
                       <_dispatch_main_queue_callback_4CF+2096>
                        <<redacted>+12>
                         <<redacted>+1628>
                          <CFRunLoopRunSpecific+384>
                           <GSEventRunModal+180>
                            <UIApplicationMain+204>
                             <main+76>
<Error>: CGContextSaveGState: invalid context 0x15a913850. Backtrace:
      <<redacted>+420>
       <<redacted>+364>
        <<redacted>+788>
         <-[GMSCALayer renderInContext:]+224>
          <-[GMSMapLayer renderInContext:]+128>
           <<redacted>+364>
            <<redacted>+788>
             <<redacted>+364>
              <<redacted>+788>
               <<redacted>+364>
                <<redacted>+788>
                 <<redacted>+364>
                  <<redacted>+788>
                   <<redacted>+364>
                    <<redacted>+788>
                     <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                      <_dispatch_call_block_and_release+24>
                       <_dispatch_client_callout+16>
                        <_dispatch_main_queue_callback_4CF+2096>
                         <<redacted>+12>
                          <<redacted>+1628>
                           <CFRunLoopRunSpecific+384>
                            <GSEventRunModal+180>
                             <UIApplicationMain+204>
                              <main+76>
<Error>: CGContextSaveGState: invalid context 0x15a913850. Backtrace:
      <<redacted>+392>
       <<redacted>+768>
        <<redacted>+364>
         <<redacted>+788>
          <-[GMSCALayer renderInContext:]+224>
           <-[GMSMapLayer renderInContext:]+128>
            <<redacted>+364>
             <<redacted>+788>
              <<redacted>+364>
               <<redacted>+788>
                <<redacted>+364>
                 <<redacted>+788>
                  <<redacted>+364>
                   <<redacted>+788>
                    <<redacted>+364>
                     <<redacted>+788>
                      <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                       <_dispatch_call_block_and_release+24>
                        <_dispatch_client_callout+16>
                         <_dispatch_main_queue_callback_4CF+2096>
                          <<redacted>+12>
                           <<redacted>+1628>
                            <CFRunLoopRunSpecific+384>
                             <GSEventRunModal+180>
                              <UIApplicationMain+204>
                               <main+76>
<Error>: CGContextClipToRect: invalid context 0x15a913850. Backtrace:
      <<redacted>+580>
       <<redacted>+768>
        <<redacted>+364>
         <<redacted>+788>
          <-[GMSCALayer renderInContext:]+224>
           <-[GMSMapLayer renderInContext:]+128>
            <<redacted>+364>
             <<redacted>+788>
              <<redacted>+364>
               <<redacted>+788>
                <<redacted>+364>
                 <<redacted>+788>
                  <<redacted>+364>
                   <<redacted>+788>
                    <<redacted>+364>
                     <<redacted>+788>
                      <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                       <_dispatch_call_block_and_release+24>
                        <_dispatch_client_callout+16>
                         <_dispatch_main_queue_callback_4CF+2096>
                          <<redacted>+12>
                           <<redacted>+1628>
                            <CFRunLoopRunSpecific+384>
                             <GSEventRunModal+180>
                              <UIApplicationMain+204>
                               <main+76>
<Error>: CGContextBeginTransparencyLayerWithRect: invalid context 0x15a913850. Backtrace:
      <CGContextBeginTransparencyLayer+172>
       <<redacted>+592>
        <<redacted>+768>
         <<redacted>+364>
          <<redacted>+788>
           <-[GMSCALayer renderInContext:]+224>
            <-[GMSMapLayer renderInContext:]+128>
             <<redacted>+364>
              <<redacted>+788>
               <<redacted>+364>
                <<redacted>+788>
                 <<redacted>+364>
                  <<redacted>+788>
                   <<redacted>+364>
                    <<redacted>+788>
                     <<redacted>+364>
                      <<redacted>+788>
                       <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                        <_dispatch_call_block_and_release+24>
                         <_dispatch_client_callout+16>
                          <_dispatch_main_queue_callback_4CF+2096>
                           <<redacted>+12>
                            <<redacted>+1628>
                             <CFRunLoopRunSpecific+384>
                              <GSEventRunModal+180>
                               <UIApplicationMain+204>
                                <main+76>
<Error>: CGContextSetFillColorSpace: invalid context 0x15a913850. Backtrace:
      <<redacted>+76>
       <<redacted>+260>
        <<redacted>+636>
         <<redacted>+768>
          <<redacted>+364>
           <<redacted>+788>
            <-[GMSCALayer renderInContext:]+224>
             <-[GMSMapLayer renderInContext:]+128>
              <<redacted>+364>
               <<redacted>+788>
                <<redacted>+364>
                 <<redacted>+788>
                  <<redacted>+364>
                   <<redacted>+788>
                    <<redacted>+364>
                     <<redacted>+788>
                      <<redacted>+364>
                       <<redacted>+788>
                        <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                         <_dispatch_call_block_and_release+24>
                          <_dispatch_client_callout+16>
                           <_dispatch_main_queue_callback_4CF+2096>
                            <<redacted>+12>
                             <<redacted>+1628>
                              <CFRunLoopRunSpecific+384>
                               <GSEventRunModal+180>
                                <UIApplicationMain+204>
                                 <main+76>
<Error>: CGContextSetStrokeColorSpace: invalid context 0x15a913850. Backtrace:
      <<redacted>+88>
       <<redacted>+260>
        <<redacted>+636>
         <<redacted>+768>
          <<redacted>+364>
           <<redacted>+788>
            <-[GMSCALayer renderInContext:]+224>
             <-[GMSMapLayer renderInContext:]+128>
              <<redacted>+364>
               <<redacted>+788>
                <<redacted>+364>
                 <<redacted>+788>
                  <<redacted>+364>
                   <<redacted>+788>
                    <<redacted>+364>
                     <<redacted>+788>
                      <<redacted>+364>
                       <<redacted>+788>
                        <__54-[ICMMessengerPresentationController updateSnapshots:]_block_invoke+560>
                         <_dispatch_call_block_and_release+24>
                          <_dispatch_client_callout+16>
                           <_dispatch_main_queue_callback_4CF+2096>
                            <<redacted>+12>
                             <<redacted>+1628>
                              <CFRunLoopRunSpecific+384>
                               <GSEventRunModal+180>
                                <UIApplicationMain+204>
                                 <main+76>
(lldb)

**Comment by bboyle18** [comment] 2016-09-08 09:20
Hi @Mencls 👋

Thanks for logging this issue. I'm going to investigate this, but I have a couple of questions.
- Is this crash consistently reproducible? 
- Does it only happen on the conversation list screen?

Thanks

Brian

**Comment by Mencls** [comment] 2016-09-09 00:19
Hi @bboyle18, thanks for your answer. Yes the crash happens every time I put my phone in landscape mode, on conversation list screen and conversation screen as well.

**Comment by Mencls** [comment] 2016-10-07 02:43
Hi @bboyle18, were you able to reproduce the bug?

**Comment by bboyle18** [comment] 2016-10-07 09:50
Hi @Mencls 👋 

Unfortunately, we weren't able to reproduce it.
We created sample app (https://github.com/intercom/intercom-cordova/tree/master/Example) and it works fine. I'd be interested to see if you could compile that sample app and see if you get the same problem?

Cheers

Brian

**Comment by bboyle18** [comment] 2016-11-03 13:07
Closing as we are unable to reproduce. Please feel free to reopen if you can provide more info to help us detect this issue.
Cheers
Brian

**Closed by bboyle18** 2016-11-03 13:07 UTC
