### ISSUE TITLE
Doesn't build with latest Android Support Library (26.1.0)

### ISSUE THREAD

**Issue by edwardsilhol** [intercom/intercom-cordova#205] opened 2017-09-18 09:43 UTC
## Version info

  - Intercom for Cordova/PhoneGap version: 6.2.3
  - iOS/Android OS version: latest
  - iOS/Android Device: irrelevant

## Expected behavior

Should build.

## Actual behavior

Build fails, as plugin requires a different version of android support library (6.0.2) than that which is installed via Maven (6.1.0).

See logs below.

## Steps to reproduce

 1. Try to build app with latest version of android support library

## Logs

```
Error: /Users/.../cordova/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/.../cordova/platforms/android/AndroidManifest.xml:28:13-35 Error:
	Attribute meta-data#android.support.VERSION@value value=(26.0.2) from [com.android.support:design:26.0.2] AndroidManifest.xml:28:13-35
	is also present at [com.android.support:support-v4:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.2) from [com.android.support:design:26.0.2] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:support-v4:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.
```

**Comment by ronocod** [comment] 2017-09-18 09:59
Hi, do you know what's causing your app to use version 26.1.0 of the v4 support library? Our SDK depends on version 26.0.2 of a couple of the support library but it works fine with 26.1.0, as long as all the support library dependencies use the same version.

**Comment by NickMele** [comment] 2017-09-21 17:43
I am running into this same exact error. Do you know what could be causing it? What can I get you that will help you resolve it? This is critical for us as the previous version (3.2.2) is crashing for us on android and we need to get it fixed. Please help ASAP.

**Comment by ronocod** [comment] 2017-09-22 09:19
Could you upload the contents of your `config.xml` so we can see what plugins you're using?

**Comment by NickMele** [comment] 2017-09-22 11:52
Here are the plugins we are using. If the full config.xml will help besides just seeing the plugins, i can upload that.

branch-cordova-sdk
com.verso.cordova.clipboard
cordova-background-geolocation
cordova-custom-config
cordova-fabric-plugin
cordova-plugin-app-event
cordova-plugin-app-version
cordova-plugin-applepay
cordova-plugin-appsee
cordova-plugin-background-app 2.
cordova-plugin-background-fetch
cordova-plugin-cocoalumberjack
cordova-plugin-console
cordova-plugin-crosswalk-webview
cordova-plugin-datepicker
cordova-plugin-device
cordova-plugin-facebook4
cordova-plugin-globalization
cordova-plugin-inappbrowser
cordova-plugin-intercom
cordova-plugin-market
cordova-plugin-mixpanel
cordova-plugin-multidex
cordova-plugin-network-information
cordova-plugin-splashscreen
cordova-plugin-statusbar
cordova-plugin-transport-security
cordova-plugin-vibration
cordova-plugin-whitelist
cordova-plugin-x-socialsharing
es6-promise-plugin
ionic-plugin-deploy
ionic-plugin-keyboard
onesignal-cordova-plugin
phonegap-plugin-push

**Comment by emc2spider** [comment] 2017-09-25 13:28
Hi, I'm having the same issue.
So far the only thing I've come to conclude is some sort of conflict with the phonegap-plugin-push. There is an [issue ongoing](https://github.com/intercom/intercom-cordova/issues/203) for someone using firebase, but I'm not so either the issue is unrelated or this is a different thing.
The worst part is that now not even rolling back to 3.2.2 seems to work.

**Comment by NickMele** [comment] 2017-09-25 14:18
@ronocod any status on this?

**Comment by emc2spider** [comment] 2017-09-25 15:54
ok as silly as it sounds I just followed what the error message said and added `cordova.system.library.7=com.android.support:design:26.1.0` to my project.properties file....
It compiled! 🙄
Why is that library required? What is it being used for? Who knows.... Is it the best way to solve it? probably not, but I'm pressed with time to produce a working build. If anyone else has a more elegant / robust / accurate solution I'm up for changes.
@NickMele @ronocod let me know if you have any better alternatives 😁

**Comment by NickMele** [comment] 2017-09-25 16:00
@emc2spider interesting. Where in your error log did you see to add that? I am hesitant to do that since the file says do not modify and can get overwritten at any time.

**Comment by emc2spider** [comment] 2017-09-25 16:07
@NickMele It doesn't exactly, but is the odd one out so to speak:
```Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.2) from [com.android.support:design:26.0.2] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:support-v4:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).```
So it claims that it's taking the 2.0.2 version from *`[com.android.support:design:26.0.2]`* which means that library is being required somewhere but the version found is not the correct one.
Now I couldn't find a match for that in my entire project so I just added it.

About changing the project.properties: I've discovered the file gets altered when you install / update the plugins and the dependencies are added here. But it usually adds stuff it doesn't replace anything you change, now if you've changed a library requirement and a new plugin has an instruction to add it here, it might end up duplicated so you'll end up having to clean it up after install.

**Comment by NickMele** [comment] 2017-09-25 16:32
Crazy, that seems to be working. I need to get this build out just like you so I think this is a great temp solution. But considering that this issue never arose until this latest intercom release and the fact that this is not a solid solution. I think we still need a better solution from @ronocod, or an explanation as to what other library could be causing this issue.

**Comment by NickMele** [comment] 2017-09-25 16:44
Thanks @emc2spider, not sure if you saw my previous comment!

**Comment by ronocod** [comment] 2017-09-27 10:17
In the 4.0.4 release of our Android SDK we used version 26.0.2 of a number of the Android Support Libraries. What happened here is that one of the plugins mentioned has bumped the version of one of them (v4) to version 26.1.0 in their app. You can’t build your app with mixed Support Library versions so this caused the build to fail. One solution is to find the plugin that caused the newer version to be used and remove it. 

Another one is to make our SDK always use the latest version of the Support Libraries. This could work, but is likely to cause crashes when there is a new major version of the Support Libraries released.

I'll look into a better long-term solution for this. In the meantime we've released version 4.0.5 of our Android SDK which uses version 26.1.0 of the Support Libraries so this should be fixed for now.

**Comment by NickMele** [comment] 2017-09-27 16:50
Thanks for the update @ronocod. I will be trying this out soon.

**Comment by NickMele** [comment] 2017-09-28 14:18
@ronocod that seems to have fixed the issue. I no longer need the temp fix mentioned above. @emc2spider you should give it a shot as well, but i think this issue can be closed.

**Comment by emc2spider** [comment] 2017-09-28 16:47
Thanks for the update @ronocod I'll give it a shot now. I didn't open the issue but you guys can close it if you think is sorted already :)

**Closed** 2017-09-28 17:02 UTC
