### ISSUE TITLE
no close button 

### ISSUE THREAD

**Issue by greggreenhaw** [intercom/intercom-cordova#199] opened 2017-08-29 19:16 UTC
calling intercom.displayMessenger(); 
opens a full screen window without a close button

**Comment by bboyle18** [comment] 2017-08-29 19:24
Hi @greggreenhaw 👋 

Can you share a screenshot of this issue please?

Thanks

Brian

**Comment by greggreenhaw** [comment] 2017-08-29 21:13
[image: Inline image 1]

**Comment by bboyle18** [comment] 2017-08-29 21:16
Hi @greggreenhaw 
That image didn't seem to attach. 😞

**Comment by bboyle18** [comment] 2017-09-01 08:42
Hi @greggreenhaw 👋 

Did you manage to resolve this issue?
If not, can you please attached the screenshot you mentioned?
We should be able to fix any problems once we see it.

💪 

Brian

**Comment by greggreenhaw** [comment] 2017-09-01 14:37
Dam I send another email with it attached I'll try again later

Greg Greenhaw 
310.869.0301

**Comment by bboyle18** [comment] 2017-09-05 20:55
Closing issue as no response from customer.
@greggreenhaw Feel free to reopen if you can provide us with a screenshot and steps to reproduce.

Brian

**Comment by greggreenhaw** [comment] 2017-09-05 23:30
Does this work?


[image: Inline image 1]

**Comment by bboyle18** [comment] 2017-09-05 23:47
@greggreenhaw No it doesn't. I notice that you are trying to attach an image via email.
I suggest you use the Github website to attach any images.

**Comment by greggreenhaw** [comment] 2017-09-06 01:42
![pic](https://user-images.githubusercontent.com/1399863/30090687-0e19165a-9283-11e7-968a-1b2b757c76a8.jpg)

**Comment by greggreenhaw** [comment] 2017-09-06 01:42
done

**Comment by bboyle18** [comment] 2017-09-06 11:25
The problem is is that Intercom.bundle which contains all Intercom's strings is not being loaded correctly.
Can you try the [steps outlined here](https://github.com/intercom/intercom-cordova/issues/161#issuecomment-290089078)?
Theres sometimes issues with Cordova that requires these steps to be completed.

Let me know you get on.

Cheers
Brian

**Comment by greggreenhaw** [comment] 2017-09-06 12:32
We did not want to use the bubble in the app because its affecting our layout. I added a custom open button

**Comment by greggreenhaw** [comment] 2017-09-06 14:55
I ran the commands and the pods direct has the fields but when I open the
xcode project the directory is empty do I have to run cordova prepare or
something?

**Comment by bboyle18** [comment] 2017-09-06 14:59
You need to open the Xcode `.xcworkspace` file to open the project correctly.

**Comment by bboyle18** [comment] 2017-09-14 20:42
Hi @greggreenhaw 👋 
Can you please let me know if you have resolved this so that I can close this issue?

Thanks

Brian

**Comment by greggreenhaw** [comment] 2017-09-14 21:05
Resolved thank you

**Closed** 2017-09-14 21:30 UTC
