### ISSUE TITLE
New Message Bubble is Behind Webview Elements on Android

### ISSUE THREAD

**Issue by bryanterrell** [intercom/intercom-cordova#46] opened 2016-03-14 01:07 UTC
## Version info
  - Intercom for Cordova/PhoneGap version: 1.1.4
  - iOS/Android OS version: Android 6.0.1
  - iOS/Android Device: Google Nexus 5

## Expected behavior
New message bubble for Intercom would always be shown over any elements in the webview. We're using Crosswalk for Cordova to get better performance, which may be related.

## Actual behavior
We're using Material-UI with Meteor and unfortunately the message bubble is showing behind some of the elements (Card, App Bar and other elements, for example).

This works as expected on iOS.

**Comment by froasiooneloop** [comment] 2016-05-16 15:16
Hi there,

We're having the same problem? Was someone able to solve it?
Thanks!

**Comment by jtreanor** [comment] 2016-05-16 15:37
Hi @bryanterrell and @froasiooneloop,

Sorry for they delay here. Can you tell me if it works as expected when not using Crosswalk?

**Comment by froasiooneloop** [comment] 2016-05-16 15:49
Hi @jtreanor, we're using it under Ionic. I can send push notification perfectly and everythings seems to work well. However I can't see the Intercom Bubble, I don't know if we had a bad configuration or it just doesn't work.

Thanks!

**Comment by jtreanor** [comment] 2016-05-16 15:55
@froasiooneloop When you open the push notification, does it correctly open the Intercom conversation?

**Comment by froasiooneloop** [comment] 2016-05-16 16:09
@jtreanor Yes perfect, everything works like a charm. We tried displayMessageComposer() and displayConversationsList() and everythings works well. We send and receive messages without problems, and push notifications are working great too. We just need to make the magic intercom bubble appear, but i doesn't. We also tried with intercom.setPreviewPosition(intercom.BOTTOM_RIGHT) and intercom.setVisibility(intercom.VISIBLE) but nothing :(.

I hope you can help us!
Thanks!

**Comment by jtreanor** [comment] 2016-05-16 17:05
Thanks @froasiooneloop,

I'll ask one of my colleagues who has a deep Android knowledge to look into this.

**Comment by froasiooneloop** [comment] 2016-05-16 17:29
Hi @jtreanor,
I have tested again and if the application is closed we receive two notifications, one from our app and the other from intercom I think. If we click the notification from intercom it opens intercom windows properly. However, if we click the app notification intercom window doesn't open, it just open our app.

Hope it helps, thanks!

**Comment by bryanterrell** [comment] 2016-05-26 02:32
Hi @jtreanor,

I haven't had time to look into this - spent the last day or so tracking down the issue I just posted. If I get a chance, I will test without Crosswalk.  Thanks!

**Comment by cusackd** [comment] 2016-06-10 11:58
Hi All,

Came across this issue without crosswalk, has there been any update on this?

**Comment by DaleCantwell** [comment] 2016-09-13 16:51
I'm looking into this issue now. It looks like the plugin is deprecated https://github.com/crosswalk-project/crosswalk-cordova-android#this-repository-is-deprecated
You can go to https://crosswalk-project.org/documentation/cordova.html to use it without the plugin now.
I have tested a sample app with crosswalk and intercom and we were not hidden.
Could you try updating to the newest release https://github.com/intercom/intercom-cordova/releases (3.0.10 at the time of responding) and see if the problem is persisting?

@bryanterrell was using Material-UI with Meteor, @cusackd were you using a similar setup?

**Comment by DaleCantwell** [comment] 2016-10-04 09:21
I'm going to close this issue out as I believe it is fixed in our current releases (or possibly crosswalk updates). Let me know if you see it again and I'll look back into it. If anyone does encounter it could you send me on some additional details about your apps setup as I couldn't make it reproduce it with crosswalk myself.

**Closed by DaleCantwell** 2016-10-04 09:21 UTC
